on: [push]

jobs:
  telegraf_job:
    runs-on: ubuntu-latest
    name: A job to install Telegraf
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install Telegraf
        uses: russorat/telegraf-action@main
        with:
          telegraf_version: nightly
      - name: Run Telegraf
        run: |
          telegraf --test
          
